name = "JSync"
uuid = "0bd0ec1e-3af1-423e-a056-074a30dd57aa"
authors = ["Colin Summers <me@colinxsummers.com> and contributors"]
version = "0.1.0"

[deps]
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
