[general]
library_name = "\"libc.so.6\""
output_file_path = "../src/fanotify.jl"
module_name = "Fanotify"
export_symbol_prefixes = ["CX", "clang_"]
macro_mode = "disable"
printer_blacklist = [
    "__restrict_arr",
    "__fortify_function",
    "__SYSCALL_SLONG_TYPE",
    "__SYSCALL_ULONG_TYPE",
    "__DEV_T_TYPE",
    "__INO64_T_TYPE",
    "__OFF64_T_TYPE",
    "__RLIM64_T_TYPE",
    "__BLKCNT64_T_TYPE",
    "__FSBLKCNT64_T_TYPE",
    "__FSFILCNT64_T_TYPE",
    "__SUSECONDS64_T_TYPE",
    "__SSIZE_T_TYPE",
    "__WCHAR_MAX",
    "INT64_MIN",
    "INT64_MAX",
    "UINT64_MAX",
    "INT_LEAST64_MIN",
    "UINT_LEAST64_MAX",
    "INT_LEAST64_MAX",
    "INT_FAST64_MIN",
    "INT_FAST64_MAX",
    "UINT_FAST64_MAX",
    "INTMAX_MIN",
    "INTMAX_MAX",
    "UINTMAX_MAX",
    "__kernel_old_uid_t",
    "__kernel_old_dev_t",
    "__bitwise",
    "__INO_T_TYPE",
    "__NLINK_T_TYPE",
    "__FSWORD_T_TYPE",
    "__OFF_T_TYPE",
    "__RLIM_T_TYPE",
    "__BLKCNT_T_TYPE",
    "__FSBLKCNT_T_TYPE",
    "__FSFILCNT_T_TYPE",
    "__CLOCK_T_TYPE",
    "__TIME_T_TYPE",
    "__SUSECONDS_T_TYPE",
    "__BLKSIZE_T_TYPE",
    "__CPU_MASK_TYPE",
    "__WCHAR_MIN",
    "WCHAR_MAX",
    "__TIME64_T_TYPE",
    "WCHAR_MIN",
    "__ptr_t",
    "__TIMER_T_TYPE",
    # "__errno_location"
]
